server{
	listen 80;

	location /file {
	return 200 "Hello World $request_uri \n";
	}
	location /old {
	return 301 /file;
	}
	location /other {
	rewrite ^/other /file ;
	}
	location / {
	sub_filter "Welcome to" "WELCOME TO";
	sub_filter_once off;
	root /usr/share/nginx/html;
	index index.html;
	}


}
